### PR TITLE
Update packages/webviz-core from internal repo

### PR DESCRIPTION
**Pull request by janpaul123**
Changelog:
- Added support for streaming a second bag using the `remote-bag-url-2` query parameter in the URL. #374
- Fixed crashing on bags with topics that don't have a message definition. #373
- Various performance improvements.
- Improved caching of deserialized messages should result in fewer browser crashes.
- Added `unlimitedMemoryCache` experimental feature to load everything in memory without regard for caching limits. Useful for when you have a machine with lots of memory and you're explicitly OK with Webviz taking up a lot of it. Use at your own risk; this might crash your browser!
- Included an "Add Topics" option for adding markers to the Image panel.
- Made performance improvements to the Plot and State Transitions panels. If you notice any issues, these performance improvements can be disabled in the Experimental Features menu, under "Use a web worker to render the Plot panel".
- In the Image panel, we again filter available marker topics by the namespace of the currently selected camera.
- Added support for publishing messages over the Websocket connection using a Publish panel. #323
- Added layout undo/redo shortcuts.
- Added support for transforms from [`/tf_static`](http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20static%20broadcaster%20%28C%2B%2B%29). #336
- Deployed a faster format for displaying text in the 3D panel. You can now use `ctrl-f` (or Mac equivalent) to physically move the camera to matched text. If you notice any issues, this change can be disabled in the Experimental Features menu, under "Faster 3D Text".
- Fixed Webviz getting stuck in a reloading loop.
- Fixed not always loading messages when subscribing to a new topic when paused ("backfilling").
- Improved startup time by not making multiple requests with different topics when loading the page.
- Fix some cases in which "syncing" 3d panels could cause panels to display a blank screen.
- Switched Websocket message encoding to [cbor-raw](https://github.com/RobotWebTools/rosbridge_suite/pull/452). #361

### CODE REVIEW

**Comment by janpaul123** [comment]
Going to just merge this myself. 🙃

**Comment by MatthewSteel** [comment]
Whoops, too late :-).

Only thing I saw that I wasn't sure about was this: https://open-source-webviz-ui.s3.amazonaws.com/68b6d022829b03a2f92fa9651cab5be8b96073aa/index.html#Plot-line-graph-after-zoom.png

Looks fine otherwise though.

**Comment by janpaul123** [comment]
Yeah I noticed that one too. Going to have a look in our internal repo to make sure that that was intended.

**Comment by janpaul123** [comment]
Also sorry for being impatient, haha. I'm just trying to close out some loose ends before I start with a new task. 😄

**Pull request merged**
