### PR TITLE
Update packages/webviz-core from internal repo

### PR DESCRIPTION
**Pull request by janpaul123**
Changelog:
- Better error message when bag messages are not sorted.
- Allow limiting the number of messages in the Plot panel. #312
- Fix bug in TF follow button in 3d panel.
- More progress on new topic picker in 3d panel.
- Bunch more tiny fixes.

### CODE REVIEW

**Comment by defied** [comment]
Checked this out. Looks great. I just wonder if the 'scaling window' idea should be added in this one, or should another issue be requested? 

By scaling window, I mean a window where I can say I only want to see the past <n> time in the plot (As it appears to still display from the beginning of monitoring to the latest data received).

**Comment by janpaul123** [comment]
This should be implementing a sliding window. You will only see the latest N messages in the plot panel.

**Comment by defied** [comment]
Okay, I'm not seeing that. I've tried refreshing, I see the start of the plot as 0.8 seconds. The end of the plot is over 100 seconds and still climbing. The beginning remains at 0.8.

**Comment by defied** [comment]
image

**Comment by janpaul123** [comment]
You have to set "N" in the panel settings :)

**Comment by defied** [comment]
That's what I get for having it in the lower portion of my web browser. Lol!

Yeah, it's looking good now!

**Comment by defied** [comment]
I vertically split a plot graph, changed the right panel type to a State Transitions page.
Suddenly all of the timing went weird.
Screenshot from 2020-01-09 16-38-25

Removed the State Transition panel and the plots resumed working as expected.

Split a plot vertically again and waited for the new plot screen to load, and there was no issues found.

Added (not split from plot) a new State Transitions and the same issue occured.

**Comment by defied** [comment]
It happened again, but with only the plots. I sent data from the second topic on the plot, and when I stopped, it began to display the same unexpected result:

image

**Comment by janpaul123** [comment]
Yeah we keep all the x-axes synced so you can compare them more easily. Maybe we should add a checkbox to toggle that, too? Or just add this same feature to the State Transitions panel?

**Comment by defied** [comment]
It looks like when that topic stopped, it switched to display that node in full (orange), and the blue node was still only carrying my specified message N (400).

**Comment by janpaul123** [comment]
Haha yeah, in our systems it's not very common for topics to stop publishing. Is this something that happens often? We can also consider only keeping the last M seconds, instead of the last N messages. Or to have the N messages spread out in total over the different topics (right now it's per-topic).

**Comment by defied** [comment]
It does happen for development and testing, yes. Just hopefully not in the real world. 0]

**Comment by defied** [comment]
I think time would make more sense.
I only want to see the last N seconds, ideally.

**Comment by janpaul123** [comment]
I just realised that this doesn't only break when you have a topic that stops publishing, but also when you have topics that publish at different rates. So I agree that the time-based solution is the better one. Unfortunately it's also a bit harder to implement with the current architecture. Luckily I'm currently working on changing the architecture a bit, which should allow this to be done, but it might take a few weeks, so stay tuned. I'm not going to release this change since I think it's too broken. 😄

**Pull request closed without merging**
